//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.Checkpoint`
//!
//! This code was generated by `zbus-xmlgen` `4.0.1` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.Checkpoint.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.NetworkManager.Checkpoint",
    assume_defaults = true
)]
trait Checkpoint {
    /// Created property
    #[zbus(property)]
    fn created(&self) -> zbus::Result<i64>;

    /// Devices property
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// RollbackTimeout property
    #[zbus(property)]
    fn rollback_timeout(&self) -> zbus::Result<u32>;
}
