//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.VPN.Connection`
//!
//! This code was generated by `zbus-xmlgen` `4.0.1` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.VPN.Connection.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::{proxy, Connection, Result};

impl ConnectionProxy<'_> {
    pub async fn new_from_path(
        device_path: zbus::zvariant::OwnedObjectPath,
        connection: &Connection,
    ) -> Result<ConnectionProxy<'_>> {
        ConnectionProxy::builder(connection)
            .path(device_path)?
            .build()
            .await
    }
}

#[proxy(
    default_path = "/org/freedesktop/NetworkManager/VPN/Connection",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.VPN.Connection",
    assume_defaults = true
)]
trait Connection {
    /// VpnStateChanged signal
    #[zbus(signal, name = "vpn_state_changed")]
    fn vpn_vpn_state_changed(&self, state: u32, reason: u32) -> zbus::Result<()>;

    /// Banner property
    #[zbus(property)]
    fn banner(&self) -> zbus::Result<String>;

    /// VpnState property
    #[zbus(property)]
    fn vpn_state(&self) -> zbus::Result<u32>;
}
