//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.Device.Generic`
//!
//! This code was generated by `zbus-xmlgen` `4.0.1` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Generic.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::{Connection, Result, proxy};

impl GenericProxy<'_> {
    pub async fn new_from_path(device_path: zbus::zvariant::OwnedObjectPath, connection: &Connection) -> Result<GenericProxy<'_>> {
        GenericProxy::builder(&connection)
        .path(device_path)
        .expect("Path not found")
        .build()
        .await
    }
}
        
#[proxy(
    default_path = "/org/freedesktop/NetworkManager/Device/Generic",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.Device.Generic",
    assume_defaults = true
)]
trait Generic {
    /// HwAddress property
    #[zbus(property)]
    fn hw_address(&self) -> zbus::Result<String>;

    /// TypeDescription property
    #[zbus(property)]
    fn type_description(&self) -> zbus::Result<String>;
}
