//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.Device.WiMax`
//!
//! This code was generated by `zbus-xmlgen` `4.0.1` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.WiMax.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::{proxy, Connection, Result};

impl WiMaxProxy<'_> {
    pub async fn new_from_path(
        device_path: zbus::zvariant::OwnedObjectPath,
        connection: &Connection,
    ) -> Result<WiMaxProxy<'_>> {
        WiMaxProxy::builder(&connection)
            .path(device_path)
            .expect("Path not found")
            .build()
            .await
    }
}

#[proxy(
    default_path = "/org/freedesktop/NetworkManager/Device/WiMax",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.Device.WiMax",
    assume_defaults = true
)]
trait WiMax {
    /// GetNspList method
    fn get_nsp_list(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// NspAdded signal
    #[zbus(signal)]
    fn nsp_added(&self, nsp: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// NspRemoved signal
    #[zbus(signal)]
    fn nsp_removed(&self, nsp: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// ActiveNsp property
    #[zbus(property)]
    fn active_nsp(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Bsid property
    #[zbus(property)]
    fn bsid(&self) -> zbus::Result<String>;

    /// CenterFrequency property
    #[zbus(property)]
    fn center_frequency(&self) -> zbus::Result<u32>;

    /// Cinr property
    #[zbus(property)]
    fn cinr(&self) -> zbus::Result<i32>;

    /// HwAddress property
    #[zbus(property)]
    fn hw_address(&self) -> zbus::Result<String>;

    /// Nsps property
    #[zbus(property)]
    fn nsps(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Rssi property
    #[zbus(property)]
    fn rssi(&self) -> zbus::Result<i32>;

    /// TxPower property
    #[zbus(property)]
    fn tx_power(&self) -> zbus::Result<i32>;
}
