//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.Device.WireGuard`
//!
//! This code was generated by `zbus-xmlgen` `4.0.1` from D-Bus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.WireGuard.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::{proxy, Connection, Result};

impl WireGuardProxy<'_> {
    pub async fn new_from_path(
        device_path: zbus::zvariant::OwnedObjectPath,
        connection: &Connection,
    ) -> Result<WireGuardProxy<'_>> {
        WireGuardProxy::builder(connection)
            .path(device_path)
            .expect("Path not found")
            .build()
            .await
    }
}

#[proxy(
    default_path = "/org/freedesktop/NetworkManager/Device/WireGuard",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.Device.WireGuard",
    assume_defaults = true
)]
trait WireGuard {
    /// FwMark property
    #[zbus(property)]
    fn fw_mark(&self) -> zbus::Result<u32>;

    /// ListenPort property
    #[zbus(property)]
    fn listen_port(&self) -> zbus::Result<u16>;

    /// PublicKey property
    #[zbus(property)]
    fn public_key(&self) -> zbus::Result<Vec<u8>>;
}
