name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.75.0
          - stable
          - beta
          # - nightly

    env:
      RUSTUP_TOOLCHAIN: ${{ matrix.rust }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: swatinem/rust-cache@v2
      - name: cargo-check
        run: cargo check --locked

  fmt:
    name: format
    runs-on: ubuntu-latest

    env:
      RUSTUP_TOOLCHAIN: 1.75.0

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
          components: rustfmt
      - name: cargo-fmt
        run: cargo fmt -- --check

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.75.0
          - stable
          - beta
          # - nightly

    env:
      RUSTUP_TOOLCHAIN: ${{ matrix.rust }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: swatinem/rust-cache@v2
      - name: cargo-test
        run: cargo test --all --all-features

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    env:
      RUSTUP_TOOLCHAIN: 1.75.0

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
          components: clippy
      - uses: swatinem/rust-cache@v2
      - name: cargo-clippy
        run: cargo clippy --all --all-targets --all-features -- -D warnings

